#!/bin/sh

REMOTE_HOST=${1:-"habals.csres.utexas.edu"}
NUM=${2:-0}
PORT=$(($NUM+5900))

echo "ssh -N -R *:${PORT}:localhost:${PORT} ${REMOTE_HOST}"
read -p "Really Connect [Y/n]? " CONTINUE

if [ "$CONTINUE" != "n" ]
then
	ssh -N -R *:${PORT}:localhost:${PORT} ${REMOTE_HOST}
fi
