#!/bin/bash

_buck_completion() {
  if [[ "${BASH_VERSION:0:1}" > "3" ]] ; then
    local prev="${COMP_WORDS[$((COMP_CWORD - 1))]}"
    local cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ "$prev" == "buck" ]]; then
      COMPREPLY=( $(compgen -W 'audit autodeps build cache clean distbuild \
                                doctor fetch help install machoutils project \
                                publish query rage root run server suggest \
                                targets test uninstall verify-caches' -- "$cur") )
    elif [[ "$prev" == "@" ]]; then
      COMPREPLY=( $(compgen -P '@' -W "$(find "$cur"* -xtype f)" -- "$cur") )
    elif [[ "$prev" == ":" ]]; then
      if [[ -z "$2" ]] ; then
        local delta=1
      else
        local delta=2
      fi
      local tdir="${COMP_WORDS[$((COMP_CWORD - $delta))]}"
      if [[ -a "$tdir/BUCK" ]] ; then
        COMPREPLY=($(sed -n "s/ *name *= *['\"]\($2[a-zA-Z_-]*\)['\"].*/\1/gp" \
                    "$tdir/BUCK"))
      elif [[ -a "$tdir/TARGETS" ]] ; then
        COMPREPLY=($(sed -n "s/ *name *= *['\"]\($2[a-zA-Z_-]*\)['\"].*/\1/gp" \
                    "$tdir/TARGETS"))
      fi
    fi
  fi
}

complete -o dirnames -F _buck_completion buck
